### ISSUE TITLE
Task list test

### ISSUE THREAD

**Issue by brooksambrose** [brooksambrose/oikos#3]
- [ ] a task list item
- [x] list syntax required
- [ ] normal **formatting**, @mentions, #1234 refs
- [ ] incomplete
- [x] completed
